clear;
clc;
close all;

% Initialize project

projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(genpath(projectRoot));

cfg = defaultConfig();

% Select image

[file, path] = uigetfile( {'*.jpg', 'Road Images'}, 'Select a road image', cfg.testImageDir);

if isequal(file, 0)
    disp('Image selection cancelled.');
    return;
end

imagePath = fullfile(path, file);

%% Load and preprocess

data = loadImagePair(imagePath);

if ~data.hasGroundTruth
    error('The selected image does not have a ground-truth mask.');
end

[~, grayImage] = preprocessImage( data.image, cfg);

%% Generate raw masks

otsuRaw = detectClassical( grayImage, 'Otsu', cfg);

sauvolaRaw = detectClassical( grayImage, 'Sauvola', cfg);

cannyRaw = detectClassical( grayImage, 'Canny', cfg);

%% Generate final masks

otsuFinal = postprocessMask( otsuRaw, 'Otsu', cfg);

sauvolaFinal = postprocessMask( sauvolaRaw, 'Sauvola', cfg);

cannyFinal = postprocessMask( cannyRaw, 'Canny', cfg);

%% Calculate metrics

otsuRawMetrics = computeMetrics( otsuRaw, data.groundTruth);

otsuFinalMetrics = computeMetrics( otsuFinal, data.groundTruth);

sauvolaRawMetrics = computeMetrics( sauvolaRaw, data.groundTruth);

sauvolaFinalMetrics = computeMetrics( sauvolaFinal, data.groundTruth);

cannyRawMetrics = computeMetrics( cannyRaw, data.groundTruth);

cannyFinalMetrics = computeMetrics( cannyFinal, data.groundTruth);

%% Create comparison table

method = [ ...
    "Otsu Raw"; ...
    "Otsu Final"; ...
    "Sauvola Raw"; ...
    "Sauvola Final"; ...
    "Canny Raw"; ...
    "Canny Final"];

dice = [ ...
    otsuRawMetrics.Dice; ...
    otsuFinalMetrics.Dice; ...
    sauvolaRawMetrics.Dice; ...
    sauvolaFinalMetrics.Dice; ...
    cannyRawMetrics.Dice; ...
    cannyFinalMetrics.Dice];

iou = [ ...
    otsuRawMetrics.IoU; ...
    otsuFinalMetrics.IoU; ...
    sauvolaRawMetrics.IoU; ...
    sauvolaFinalMetrics.IoU; ...
    cannyRawMetrics.IoU; ...
    cannyFinalMetrics.IoU];

precision = [ ...
    otsuRawMetrics.Precision; ...
    otsuFinalMetrics.Precision; ...
    sauvolaRawMetrics.Precision; ...
    sauvolaFinalMetrics.Precision; ...
    cannyRawMetrics.Precision; ...
    cannyFinalMetrics.Precision];

recall = [ ...
    otsuRawMetrics.Recall; ...
    otsuFinalMetrics.Recall; ...
    sauvolaRawMetrics.Recall; ...
    sauvolaFinalMetrics.Recall; ...
    cannyRawMetrics.Recall; ...
    cannyFinalMetrics.Recall];

f1Score = [ ...
    otsuRawMetrics.F1Score; ...
    otsuFinalMetrics.F1Score; ...
    sauvolaRawMetrics.F1Score; ...
    sauvolaFinalMetrics.F1Score; ...
    cannyRawMetrics.F1Score; ...
    cannyFinalMetrics.F1Score];

accuracy = [ ...
    otsuRawMetrics.Accuracy; ...
    otsuFinalMetrics.Accuracy; ...
    sauvolaRawMetrics.Accuracy; ...
    sauvolaFinalMetrics.Accuracy; ...
    cannyRawMetrics.Accuracy; ...
    cannyFinalMetrics.Accuracy];

metricsTable = table( ...
    method, ...
    dice, ...
    iou, ...
    precision, ...
    recall, ...
    f1Score, ...
    accuracy, ...
    'VariableNames', { ...
        'Method', ...
        'Dice', ...
        'IoU', ...
        'Precision', ...
        'Recall', ...
        'F1Score', ...
        'Accuracy'});

disp(metricsTable);